/*==============================================================
Project:
COVID-19 Global Analytics

Author:
Solomon Mensah

Description:
This project explores global COVID-19 cases, deaths,
vaccination progress, and infection trends using SQL Server.

Skills Demonstrated:
✓ Data Cleaning
✓ Data Validation
✓ Joins
✓ Window Functions
✓ CTEs
✓ Temporary Tables
✓ Aggregate Functions
✓ Ranking
✓ Views
==============================================================*/


-- Create the database that will contain the COVID-19 portfolio project.
CREATE DATABASE IF NOT EXISTS PORTFOLIO_PROJECT;

-- Set the COVID-19 project database as the active database.
USE DATABASE PORTFOLIO_PROJECT;

-- Create the schema that will contain the original uploaded data.
CREATE SCHEMA IF NOT EXISTS RAW;

-- Create the schema that will contain validated and transformed data.
CREATE SCHEMA IF NOT EXISTS CLEAN;

-- Create the schema that will contain reporting views and analytical models.
CREATE SCHEMA IF NOT EXISTS ANALYTICS;

-- Set the raw-data schema as the active schema.
USE SCHEMA RAW;

-- Display the tables currently available in the raw-data schema.
SHOW TABLES IN SCHEMA PORTFOLIO_PROJECT.RAW;

-- Count the records loaded into the COVID deaths table.
SELECT COUNT(*) AS COVID_DEATHS_ROW_COUNT
FROM PORTFOLIO_PROJECT.RAW.COVID_DEATHS;

-- Count the records loaded into the COVID vaccinations table.
SELECT COUNT(*) AS COVID_VACCINATIONS_ROW_COUNT
FROM PORTFOLIO_PROJECT.RAW.COVID_VACCINATIONS;

-- Preview the first ten records from the COVID deaths table.
SELECT *
FROM PORTFOLIO_PROJECT.RAW.COVID_DEATHS
LIMIT 10;

-- Preview the first ten records from the COVID vaccinations table.
SELECT *
FROM PORTFOLIO_PROJECT.RAW.COVID_VACCINATIONS
LIMIT 10;


/*--------------------------------------------------------------
Step 2
Check for missing values
--------------------------------------------------------------*/

-- Check row counts and completeness of important columns.
-- Show all databases available to your role.
SHOW DATABASES;

-- Show all tables in the RAW schema.
SHOW TABLES IN SCHEMA PORTFOLIO_PROJECT.RAW;

-- Count populated records in key columns.
SELECT
    COUNT(*) AS TotalRows,
    COUNT(LOCATION) AS Location,
    COUNT(POPULATION) AS Population,
    COUNT(TOTAL_CASES) AS TotalCases,
    COUNT(TOTAL_DEATHS) AS TotalDeaths
FROM PORTFOLIO_PROJECT.RAW.COVID_DEATHS;

-- Display all records where continent information exists.
-- Display records where continent information exists.
SELECT *
FROM PORTFOLIO_PROJECT.RAW.COVID_DEATHS
WHERE CONTINENT IS NOT NULL
ORDER BY LOCATION, DATE;

-- Display all records where continent information exists.
SELECT *
FROM PORTFOLIO_PROJECT.RAW.COVID_DEATHS
WHERE CONTINENT IS NOT NULL
ORDER BY LOCATION, DATE;

DESC TABLE PORTFOLIO_PROJECT.RAW.COVID_DEATHS;
-- Display all tables in the RAW schema.
SHOW TABLES IN SCHEMA PORTFOLIO_PROJECT.RAW;

-- Display records where continent information exists.
SELECT *
FROM PORTFOLIO_PROJECT.RAW.COVID_DEATHS
WHERE CONTINENT IS NOT NULL
ORDER BY LOCATION, DATE;

-- Display the primary columns used throughout the COVID analysis.
SELECT
    LOCATION,
    DATE,
    TOTAL_CASES,
    NEW_CASES,
    TOTAL_DEATHS,
    POPULATION
FROM PORTFOLIO_PROJECT.RAW.COVID_DEATHS
WHERE CONTINENT IS NOT NULL
ORDER BY LOCATION, DATE;

-- Calculate likelihood of death after contracting COVID-19.
SELECT
    LOCATION,
    DATE,
    TOTAL_CASES,
    TOTAL_DEATHS,
    (TOTAL_DEATHS / NULLIF(TOTAL_CASES,0)) * 100 AS DEATH_PERCENTAGE
FROM PORTFOLIO_PROJECT.RAW.COVID_DEATHS
WHERE LOCATION ILIKE '%states%'
    AND CONTINENT IS NOT NULL
ORDER BY LOCATION, DATE;

-- Calculate percentage of population infected.
SELECT
    LOCATION,
    DATE,
    POPULATION,
    TOTAL_CASES,
    (TOTAL_CASES / NULLIF(POPULATION,0)) * 100 AS PERCENT_POPULATION_INFECTED
FROM PORTFOLIO_PROJECT.RAW.COVID_DEATHS
ORDER BY LOCATION, DATE;

-- Identify countries that experienced the highest infection rates.
SELECT
    LOCATION,
    POPULATION,
    MAX(TOTAL_CASES) AS HIGHEST_INFECTION_COUNT,
    MAX((TOTAL_CASES / NULLIF(POPULATION,0)) * 100)
        AS PERCENT_POPULATION_INFECTED
FROM PORTFOLIO_PROJECT.RAW.COVID_DEATHS
GROUP BY
    LOCATION,
    POPULATION
ORDER BY PERCENT_POPULATION_INFECTED DESC;

-- Identify countries with the highest total deaths.
SELECT
    LOCATION,
    MAX(TOTAL_DEATHS) AS TOTAL_DEATH_COUNT
FROM PORTFOLIO_PROJECT.RAW.COVID_DEATHS
WHERE CONTINENT IS NOT NULL
GROUP BY LOCATION
ORDER BY TOTAL_DEATH_COUNT DESC;

-- Compare total deaths by continent.
SELECT
    CONTINENT,
    MAX(TOTAL_DEATHS) AS TOTAL_DEATH_COUNT
FROM PORTFOLIO_PROJECT.RAW.COVID_DEATHS
WHERE CONTINENT IS NOT NULL
GROUP BY CONTINENT
ORDER BY TOTAL_DEATH_COUNT DESC;

-- Calculate global cases, deaths, and death percentage.
SELECT
    SUM(NEW_CASES) AS TOTAL_CASES,
    SUM(NEW_DEATHS) AS TOTAL_DEATHS,
    (SUM(NEW_DEATHS) / NULLIF(SUM(NEW_CASES),0)) * 100
        AS DEATH_PERCENTAGE
FROM PORTFOLIO_PROJECT.RAW.COVID_DEATHS
WHERE CONTINENT IS NOT NULL;

-- Analyze daily global COVID trends.
SELECT
    DATE,
    SUM(NEW_CASES) AS DAILY_CASES,
    SUM(NEW_DEATHS) AS DAILY_DEATHS,
    (SUM(NEW_DEATHS) / NULLIF(SUM(NEW_CASES),0)) * 100
        AS DAILY_DEATH_PERCENTAGE
FROM PORTFOLIO_PROJECT.RAW.COVID_DEATHS
WHERE CONTINENT IS NOT NULL
GROUP BY DATE
ORDER BY DATE;

-- Track cumulative vaccinations by country.
SELECT
    DEA.CONTINENT,
    DEA.LOCATION,
    DEA.DATE,
    DEA.POPULATION,
    VAC.NEW_VACCINATIONS,

    SUM(VAC.NEW_VACCINATIONS)
    OVER
    (
        PARTITION BY DEA.LOCATION
        ORDER BY DEA.DATE
    ) AS ROLLING_PEOPLE_VACCINATED

FROM PORTFOLIO_PROJECT.RAW.COVID_DEATHS DEA
JOIN PORTFOLIO_PROJECT.RAW.COVID_VACCINATIONS VAC
    ON DEA.LOCATION = VAC.LOCATION
    AND DEA.DATE = VAC.DATE
WHERE DEA.CONTINENT IS NOT NULL
ORDER BY DEA.LOCATION, DEA.DATE;

-- Use a CTE to calculate population vaccination percentages.
WITH POPVSVAC AS
(
    SELECT
        DEA.CONTINENT,
        DEA.LOCATION,
        DEA.DATE,
        DEA.POPULATION,
        VAC.NEW_VACCINATIONS,

        SUM(VAC.NEW_VACCINATIONS)
        OVER
        (
            PARTITION BY DEA.LOCATION
            ORDER BY DEA.DATE
        ) AS ROLLING_PEOPLE_VACCINATED

    FROM PORTFOLIO_PROJECT.RAW.COVID_DEATHS DEA
    JOIN PORTFOLIO_PROJECT.RAW.COVID_VACCINATIONS VAC
        ON DEA.LOCATION = VAC.LOCATION
        AND DEA.DATE = VAC.DATE
    WHERE DEA.CONTINENT IS NOT NULL
)

SELECT *,
       (ROLLING_PEOPLE_VACCINATED / NULLIF(POPULATION,0))*100
       AS PERCENT_VACCINATED
FROM POPVSVAC;


-- Create a temporary table for vaccination analysis.
CREATE OR REPLACE TEMPORARY TABLE PERCENT_POPULATION_VACCINATED AS

SELECT
    DEA.CONTINENT,
    DEA.LOCATION,
    DEA.DATE,
    DEA.POPULATION,
    VAC.NEW_VACCINATIONS,

    SUM(VAC.NEW_VACCINATIONS)
    OVER
    (
        PARTITION BY DEA.LOCATION
        ORDER BY DEA.DATE
    ) AS ROLLING_PEOPLE_VACCINATED

FROM PORTFOLIO_PROJECT.RAW.COVID_DEATHS DEA
JOIN PORTFOLIO_PROJECT.RAW.COVID_VACCINATIONS VAC
    ON DEA.LOCATION = VAC.LOCATION
    AND DEA.DATE = VAC.DATE;

-- Calculate vaccination percentage using the temporary table.
SELECT *,
       (ROLLING_PEOPLE_VACCINATED / NULLIF(POPULATION,0))*100
       AS PERCENT_VACCINATED
FROM PERCENT_POPULATION_VACCINATED;

-- Create a reusable analytical view for dashboards and reporting.
CREATE OR REPLACE VIEW PORTFOLIO_PROJECT.RAW.PERCENT_POPULATION_VACCINATED AS

SELECT
    DEA.CONTINENT,
    DEA.LOCATION,
    DEA.DATE,
    DEA.POPULATION,
    VAC.NEW_VACCINATIONS,

    SUM(VAC.NEW_VACCINATIONS)
    OVER
    (
        PARTITION BY DEA.LOCATION
        ORDER BY DEA.DATE
    ) AS ROLLING_PEOPLE_VACCINATED

FROM PORTFOLIO_PROJECT.RAW.COVID_DEATHS DEA
JOIN PORTFOLIO_PROJECT.RAW.COVID_VACCINATIONS VAC
    ON DEA.LOCATION = VAC.LOCATION
    AND DEA.DATE = VAC.DATE
WHERE DEA.CONTINENT IS NOT NULL;

-- Create country-level COVID metrics.
CREATE OR REPLACE VIEW PORTFOLIO_PROJECT.ANALYTICS.VW_COUNTRY_STATS AS

SELECT
    LOCATION,
    CONTINENT,
    POPULATION,

    MAX(TOTAL_CASES) AS TOTAL_CASES,
    MAX(TOTAL_DEATHS) AS TOTAL_DEATHS,

    MAX(TOTAL_CASES/NULLIF(POPULATION,0))*100
        AS PERCENT_POPULATION_INFECTED,

    MAX(TOTAL_DEATHS/NULLIF(TOTAL_CASES,0))*100
        AS DEATH_PERCENTAGE

FROM PORTFOLIO_PROJECT.RAW.COVID_DEATHS
WHERE CONTINENT IS NOT NULL

GROUP BY
    LOCATION,
    CONTINENT,
    POPULATION;

-- Create global COVID trends by date.
CREATE OR REPLACE VIEW PORTFOLIO_PROJECT.ANALYTICS.VW_GLOBAL_DAILY AS

SELECT
    DATE,

    SUM(NEW_CASES) AS DAILY_CASES,

    SUM(NEW_DEATHS) AS DAILY_DEATHS,

    SUM(NEW_DEATHS)
/ NULLIF(SUM(NEW_CASES),0) *100
        AS DAILY_DEATH_PERCENTAGE

FROM PORTFOLIO_PROJECT.RAW.COVID_DEATHS

WHERE CONTINENT IS NOT NULL

GROUP BY DATE;

-- Create cumulative vaccination analysis.
CREATE OR REPLACE VIEW PORTFOLIO_PROJECT.ANALYTICS.VW_VACCINATION_PROGRESS AS

SELECT

    DEA.CONTINENT,
    DEA.LOCATION,
    DEA.DATE,
    DEA.POPULATION,

    VAC.NEW_VACCINATIONS,

    SUM(VAC.NEW_VACCINATIONS)
    OVER(
        PARTITION BY DEA.LOCATION
        ORDER BY DEA.DATE
    ) AS ROLLING_PEOPLE_VACCINATED,

    (
        SUM(VAC.NEW_VACCINATIONS)
        OVER(
            PARTITION BY DEA.LOCATION
            ORDER BY DEA.DATE
        )
    )
    /NULLIF(DEA.POPULATION,0)*100

    AS PERCENT_VACCINATED

FROM PORTFOLIO_PROJECT.RAW.COVID_DEATHS DEA

JOIN PORTFOLIO_PROJECT.RAW.COVID_VACCINATIONS VAC

ON DEA.LOCATION = VAC.LOCATION
AND DEA.DATE = VAC.DATE

WHERE DEA.CONTINENT IS NOT NULL;


-- Create continent-level metrics.
CREATE OR REPLACE VIEW PORTFOLIO_PROJECT.ANALYTICS.VW_CONTINENT_STATS AS

SELECT
    CONTINENT,

    MAX(TOTAL_CASES) AS TOTAL_CASES,

    MAX(TOTAL_DEATHS) AS TOTAL_DEATHS

FROM PORTFOLIO_PROJECT.RAW.COVID_DEATHS

WHERE CONTINENT IS NOT NULL

GROUP BY CONTINENT;


